image: node:6.10.3

pages:
  cache:
    paths:
    - node_modules/

before_script:
  - npm update
  - npm install
  - apt-get update -yq
  - apt-get install -y rubygems ruby-dev
  - gem install dpl
  only:
  - master

stages:
  - deploy

staging:
  stage: deploy
  - dpl --provider=heroku --app=transportation-api --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
