image: node:6.10.3

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm update
  - npm install 
  artifacts:
    paths:
    - public
  only:
  - master
staging:
  stage: deploy
  script:
  - apt-get update -yq
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=transportation-api --api-key=$HEROKU_STAGING_API_KEY
